### ISSUE TITLE
Dual License

### ISSUE THREAD

**Issue by mkaz** [RedVentures/reduce#2]
We are working on open sourcing our app (WordPress.com) and `reduce-component` is a dependency. We are planning on using the GPLv2 license, however I'm told it is incompatible with the Apache 2.0 license. 

Would it be possible to dual license this under a MIT license?

**Comment by colinmutter** [comment]
Yes this is doable. Should be able to get this updated shortly.

**Comment by colinmutter** [comment]
Updated in 6df9f93219a702f1511a3114fa1f3867040fd5b0

**Comment by mkaz** [comment]
👍🏻 Thank you so much, big help!
